### ISSUE TITLE
要怎么在本地运行[Discussion] your question

### ISSUE THREAD

**Issue by ZTMIDGO** [zxkmm/gpt2-ml-fixed#8]
没办法在本地运行

**Comment by zxkmm** [comment]
您好：
1.把仓库克隆到本地
2.在modules目录底下建一个mega目录
3.下载release底下的两个文件放到mega目录
4.带min_len和sp_num两个参数，以及ckpt_fn参数+release预训练库一共三个参数运行主程序，入口在demo.py
（显卡可能需要RTX旗舰卡，不然会超时异常，如果有报错信息也可以一并贴上来）
以上。

**Comment by zxkmm** [comment]
以下是依赖关系
```
Ubuntu 18.04.5和以上
pandas==0.24.2
regex==2019.4.14
h5py==2.10.0
numpy==1.18.4
tensorboard==1.15.0
tensorflow-gpu==1.15.4
tensorflow-estimator==1.15.1
tqdm==4.31.1
requests==2.22.0
ujson==2.0.3
protobuf==3.19.4
```

**Comment by ZTMIDGO** [comment]
@zxkmm 谢谢，因为我用PyCharm没有tensorflow-gpu==1.15.4版本，只有1.15.0，所以我安装了2.1.0版本导致没办法运行，我重新安装了1.15.0，可以运行了，非常感谢。

**Comment by zxkmm** [comment]
> @zxkmm 谢谢，因为我用PyCharm没有tensorflow-gpu==1.15.4版本，只有1.15.0，所以我安装了2.1.0版本导致没办法运行，我重新安装了1.15.0，可以运行了，非常感谢。

不客气，谢谢您的使用，谢谢原作者写的大部分代码
