### ISSUE TITLE
请教一下，关于转换成为tflite格式后运行得到的结果是乱码

### ISSUE THREAD

**Issue by ZTMIDGO** [zxkmm/gpt2-ml-fixed#9]
我把模型转换成为了tflite模型，但不知道要怎么才能够和您写的代码得到正确的结果一样。

**Comment by zxkmm** [comment]
您好，实在抱歉，解决这个可能工程量稍微有点大。不过如果是简单的问题的话或许可以简单处理一下，请问乱码是什么样子的乱码呢？以及这个模型的性能比较差，不是很确定在嵌入式/移动能不能有正常的性能。如果是生产的话我个人感觉还是用openai的api或者可以尝试一下 @BlinkDL 大佬写的RWKV 模型，性能会好很多。https://github.com/BlinkDL/AI-Writer/issues/1#issuecomment-923849131

**Comment by ZTMIDGO** [comment]
前一段时间了解过AI-Writer。Ai-write和gpt2-ml是我目前接触到的最好的中文模型，但无法移植到移动端使用。折腾了三天，有点累。如果您会Android编程，可以一起探讨一下：https://github.com/huggingface/tflite-android-transformers
目前安卓端可以跑gpt2模型为17亿参数的模型，序列长度为128个单词。

**Comment by zxkmm** [comment]
哇，好厉害！感谢您的推荐！我明天看一看

**Comment by BlinkDL** [comment]
AI-Writer有onnx版本（那个A卡版就是），在移动端应该可以直接跑。

**Comment by BlinkDL** [comment]
@ZTMIDGO 欢迎加RWKV开发QQ群 325154699 谢谢

**Comment by zxkmm** [comment]
@BlinkDL 谢谢
